version: '3.8'

services:
  mysql:
    image: cerrajeria-sql:latest
    container_name: mysql
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql  # opcional, si tienes script
    ports:
      - "3306:3306"
    networks:
      - cerrajeria-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  app:
    image: cerrajeria-app:latest
    container_name: app
    environment:
      DB_HOST: mysql
      DB_NAME: seguridad_db
      DB_USER: usuario_app
      DB_PASSWORD: apppassword
    networks:
      - cerrajeria-net
    depends_on:
      mysql:
        condition: service_healthy
    # Si la app es interactiva y necesitas ver logs, usa:
    # stdin_open: true
    # tty: true

volumes:
  mysql-data:

networks:
  cerrajeria-net:
