apiVersion: v1
kind: Pod
metadata:
  name: java-pod-simple
  labels:
    app: java-app
spec:
  containers:
  - name: java-container
    image: mi-java-app:latest  # Nombre que usarás al construir
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
    env:
    - name: JAVA_OPTS
      value: "-Xms32m -Xmx64m"
